version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - mysql-data:/var/lib/mysql    #データの永続化のために必要
    ports:
      - "4306:3306"  #両方3306でもok。詳細は下の「番外編：DBをsequel proで可視化したい」へ

  app:
    tty: true          #コンテナ上でbinding.pryするために必要
    stdin_open: true   #コンテナ上でbinding.pryするために必要
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/superd_view    #ローカルのディレクトリをコンテナ上にマウント
      - bundle:/usr/local/bundle    #bundle installした後buildし直さなくてよくなる
      - public-data:/superd_view/public
      - tmp-data:/superd_view/tmp
      - log-data:/superd_view/log
    ports:
      - "3000:3000"
    links:
      - db

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/superd_view/public
      - tmp-data:/superd_view/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
  bundle:      #bundle installした後buildし直さなくてよくなる