version: '2'
services:
  db:
    image: mysql:5.6
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/superd_view
      - public-data:/superd_view/public
      - tmp-data:/superd_view/tmp
      - log-data:/superd_view/log

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/superd_view/public
      - tmp-data:/superd_view/tmp
    ports:
      - 80:80
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data: