version: '2'
services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    environment:
      RAILS_ENV: production

  web:
    extends:
      file: docker-compose.yml
      service: web
    depends_on:
      - app
volumes:
  public-data:
  bundle:
  tmp-data:
  log-data: