version: 2
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    working_directory: ~/superd_view
    steps:
      - checkout
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose -f test.yml up -d
      - run:
          name: データベースのセットアップ
          command: docker-compose exec app bundle exec rails db:create db:migrate RAILS_ENV=test --trace
      - run:
          name: RSpecテスト実行
          command: docker-compose run app bundle exec bin/rspec
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down