default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: superd_view_development

test:
  <<: *default
  database: superd_view_test
  host: 127.0.0.1

production:
  <<: *default