default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: db

development:
  <<: *default
  database: superd_view_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: superd_view_test
  socket: /tmp/mysql.sock
  host: <%= ENV['MYSQL_HOST'] %>

production:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>
