default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  host: db

development:
  <<: *default
  database: superd_view_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: superd_view_test
  socket: /tmp/mysql.sock
  host: <%= ENV['MYSQL_HOST'] %>

production:
  <<: *default
  database: superd_view_production
  username: superd_view
  password: <%= ENV['SUPERD_VIEW_DATABASE_PASSWORD'] %>
